steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/git123/my-app:${SHORT_SHA:-latest}'  # ✅ Default to 'latest' if SHORT_SHA is empty
      - '.'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/git123/my-app:${SHORT_SHA:-latest}'  # ✅ Default to 'latest'

  # Step 3: Authenticate kubectl with GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-cluster'
      - '--zone=us-central1-a'
      - '--project=git123'

  # Step 4: Deploy the updated image using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/my-app-deployment'
      - 'my-app=gcr.io/git123/my-app:${SHORT_SHA:-latest}'  # ✅ Default to 'latest'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
