apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-apps
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: my-apps
  template:
    metadata:
      labels:
        app: my-apps
    spec:
      containers:
        - name: my-apps  # Container name updated
          image: gcr.io/git123/my-apps:latest  # Ensure this matches your GCR image
          ports:
            - containerPort: 80  # Update if your app uses a different port
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
