apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2  # Number of pod instances
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-apps  # Container name must match in Cloud Build
          image: gcr.io/git123/my-app:latest  # Correct project ID and image name
          ports:
            - containerPort: 8080  # Exposed port inside the container
