apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-apps
          image: gcr.io/git123/my-apps:latest  # Replace with your project ID
          ports:
            - containerPort: 8080  # Port inside the container
