apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer  # Change to ClusterIP if needed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
