apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # This should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80        # Exposed port on the service
      targetPort: 80  # Port the container is listening on
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
