apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-apps
  ports:
    - port: 80  # Exposed port
      targetPort: 8080  # Container's internal port
  type: LoadBalancer  # External access to the service
