apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer  # Use ClusterIP for internal access or NodePort if needed
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8080  # Matches container port in Deployment
