apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-apps  # Match the deployment label
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 80  # Internal container port
  type: LoadBalancer  # Use "ClusterIP" if not exposing externally
